server:
  port: 8064
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

spring:     
  data:
   mongodb:
      database: ducat-assignment 
      port: 27017
      host: localhost




